FROM rycus86/arm64v8-alpine-qemu

LABEL maintainer "Viktor Adam <rycus86@gmail.com>"

RUN apk --no-cache add python py2-pip

ADD requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

ADD docker-requirements.txt /tmp/docker-requirements.txt
RUN pip install -r /tmp/docker-requirements.txt

ADD src /app
WORKDIR /app

ENTRYPOINT [ "python", "app.py"]